# Homework 3 - Data viz

###TODO

In [30]:
import os
import pandas as pd
import json
import folium

import folium

In [31]:
folium.__version__ == '0.5.0'

True

Short Description: 

(Using Table tec00112 that presents data on employment, based on the domestic concept.)
Employment covers all persons engaged in some productive activity that falls within the production boundary 
of the national accounts. Employed persons are either employees (persons who work by agreement, work for a 
resident institutional unit and receive a remuneration recorded as compensation of employees) or self-employed
(persons who are the sole owners, or joint owners, of the unincorporated enterprises in which they work, excluding
 those unincorporated enterprises that are classified as quasi-corporations).The domestic concept of employment
includes both the residents and the non-residents who work for resident producer units.

In [32]:
FILE_PATH = "data/"

In [33]:

df = pd.DataFrame()
df = df.append( pd.read_csv("data/tec00112.tsv", sep="\t" , header=0))
df.columns = [i.split(" ")[0] for i in df.columns]
df.columns = [i.split("\\")[0] for i in df.columns]
p = df['unit,nace_r2,na_item,geo'].str.split(",")
df['unit,nace_r2,na_item,geo'] = [pi[3] for pi in p]
df

,"unit,nace_r2,na_item,geo",2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,AT,3872.90,3940.73,4012.73,4089.13,4067.50,4098.21,4161.95,4205.16,4219.77,4259.90,4285.36,4337.23
1,BE,4255.30,4302.90,4374.00,4453.00,4445.60,4474.10,4535.40,4555.10,4540.20,4560.00,4600.50,4658.10
2,BG,3495.27,3612.04,3726.74,3814.65,3749.30,3603.89,3524.55,3436.39 p,3421.58 p,3434.17 p,3446.21 p,3463.35 p
3,CH,4144.66,4234.93,4344.27,4448.26,4469.11,4479.68,4593.85,4674.18,4733.21,4822.94,4899.75,4969.93
4,CY,366.46,373.25,389.77,403.51,403.64,405.58,405.68,392.75,369.49,362.95,368.37,379.93 p
5,CZ,4922.64,4988.98,5093.14,5204.08,5110.10,5057.24,5043.44,5064.62,5080.93,5108.97,5181.91,5248.55
6,DE,39326.00,39635.00,40325.00,40856.00,40892.00,41020.00,41577.00,42061.00,42319.00,42672.00,43069.00,43638.00
7,DK,2783.00,2846.00,2912.00,2947.00,2854.00,2788.00,2787.00,2767.00,2766.00,2794.00,2829.00,2877.00
8,EA,140820.92,143274.00,146917.17,148694.59,148352.20,147667.80,148410.83,147719.45,146778.10,148544.96,151373.14,153393.23
9,EA18,145938.49,148544.43,151348.33,152638.90,149832.52,149059.40,149267.05,148588.08,147666.73,148544.96,150038.41,152032.02
10,EA19,147359.20,149960.69,152793.47,154064.99,151149.03,150306.17,150519.76,149862.98,148958.62,149862.77,151373.14,153393.23
11,EE,612.30,642.20,643.40,642.10,576.60,548.10,584.00,593.50,600.90,605.50,622.90,624.70
12,EL,4646.87,4731.34,4795.07,4856.36,4829.00,4705.48,4381.82 p,4105.22 p,3997.71 p,4034.84 p,4064.04 p,4083.03 p
13,ES,19784.00,20609.20,21284.90,21324.10,19986.80,19639.50,19112.50,18342.60,17861.90,18039.20,18521.30 p,18987.40 p
14,EU28,220897.89,224686.64,228889.84,231215.63,227222.35,225675.48,225986.40,225123.43,224528.80,226843.03,229324.65,232135.67
15,FI,2410.60,2454.60,2506.90,2562.70,2501.00,2483.80,2515.50,2537.60,2519.60,2507.50,2504.10,2516.60
16,FR,26374.00,26664.00,27039.00,27166.00,26859.00,26888.00,27099.00,27185.00,27252.00,27373.00,27434.00 p,27612.00 p
17,HR,1637.54 p,1689.26 p,1742.67 p,1779.87 d,1766.55 d,1699.97 d,1634.51 d,1575.51 d,1533.99 d,1575.00 d,1594.59 d,1599.19 d
18,HU,4174.19,4192.22,4197.97,4115.47,4012.92,3969.25,3969.42,3975.80,4019.46,4213.65,4315.55,4429.45
19,IE,1962.30,2053.00,2142.74,2129.25,1962.30,1882.73,1872.44 b,1861.51,1908.27,1940.41,1989.41,2045.45
20,IT,24501.30,24983.80,25294.90,25349.20,24925.50,24765.70,24842.70,24764.80,24322.80,24339.40,24497.90,24809.40
21,LI,:,:,:,:,:,:,:,:,36.22,36.68,36.76,:
22,LT,1420.72,1416.26,1445.14,1426.09,1316.51,1246.77,1252.70,1274.90,1291.89,1317.81,1334.73,1361.21
23,LU,307.69,319.48,333.55,349.46,353.12,359.56,370.16,379.14,386.07,395.95,406.11,418.44
24,LV,969.15,1024.95,1064.07,1055.07,903.72,843.51,856.22,868.63,888.63,876.63,889.00,886.30
25,MK,587.48,614.58,632.90,682.96,713.08,687.38,697.09,705.38,744.84,762.51,:,:
26,MT,151.26,153.51,156.95,160.94,161.00,163.79,168.62,172.83,179.28,188.51,195.93,203.15
27,NL,8339.00,8519.00,8771.00,8914.00,8838.00,8778.00,8854.00,8836.00,8732.00,8724.00,8806.00 p,8901.00 p
28,NO,2354.00,2434.00,2535.00,2617.00,2605.00,2591.00,2630.00,2684.00,2713.00,2746.00,2757.00,2764.00
29,PL,14057.00,14503.90,15155.90,15731.90,15789.40,15370.30 b,15457.30,15474.90,15463.80,15731.00,15970.00,16060.70 p
30,PT,5040.96,5060.86,5061.58,5080.13,4941.69,4871.33,4776.73,4581.45,4450.17,4512.99,4575.82,4650.51 p
31,RO,9267.20,9330.70,9364.80,9365.90,9181.00,9156.10,9082.20,8645.30 b,8569.40,8634.60,8525.70,8449.00 p
32,SE,4348.70,4422.40,4524.40,4565.20,4454.80,4497.70,4593.60,4627.40,4671.80,4737.40,4807.40,4889.80
33,SI,929.49,944.14,975.80,1000.82,982.90,962.10,946.02,937.24,926.70,930.03,941.56,959.74
34,SK,2088.91,2132.39,2176.97,2247.14,2203.16,2169.82,2208.31,2209.43,2192.25,2223.15,2267.10,2321.05
35,UK,28853.15,29140.45,29378.75,29627.56,29154.26,29226.87,29374.62,29694.53,30042.22,30752.41,31281.15,31725.39

In [37]:
STUPID_NAME = '2016'
STUPID_NAME_2 = 'unit,nace_r2,na_item,geo'
reg_ex = "p|d|:"

def clean_unemployed_column(df, column_name):
    for i in range(df[column_name].shape[0]):
        df[column_name][i] =  df[column_name][i].split("p")[0]
        df[column_name][i] =  df[column_name][i].split("d")[0]
        df[column_name][i] =  df[column_name][i].split(":")[0]
    
clean_unemployed_column(df, STUPID_NAME)
clean_unemployed_column(df, STUPID_NAME_2)

df[STUPID_NAME].fillna(0, inplace = True)
df

,"unit,nace_r2,na_item,geo",2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,State
0,AT,3872.90,3940.73,4012.73,4089.13,4067.50,4098.21,4161.95,4205.16,4219.77,4259.90,4285.36,4337.23,AT
1,BE,4255.30,4302.90,4374.00,4453.00,4445.60,4474.10,4535.40,4555.10,4540.20,4560.00,4600.50,4658.10,BE
2,BG,3495.27,3612.04,3726.74,3814.65,3749.30,3603.89,3524.55,3436.39 p,3421.58 p,3434.17 p,3446.21 p,3463.35,BG
3,CH,4144.66,4234.93,4344.27,4448.26,4469.11,4479.68,4593.85,4674.18,4733.21,4822.94,4899.75,4969.93,CH
4,CY,366.46,373.25,389.77,403.51,403.64,405.58,405.68,392.75,369.49,362.95,368.37,379.93,CY
5,CZ,4922.64,4988.98,5093.14,5204.08,5110.10,5057.24,5043.44,5064.62,5080.93,5108.97,5181.91,5248.55,CZ
6,DE,39326.00,39635.00,40325.00,40856.00,40892.00,41020.00,41577.00,42061.00,42319.00,42672.00,43069.00,43638.00,DE
7,DK,2783.00,2846.00,2912.00,2947.00,2854.00,2788.00,2787.00,2767.00,2766.00,2794.00,2829.00,2877.00,DK
8,EA,140820.92,143274.00,146917.17,148694.59,148352.20,147667.80,148410.83,147719.45,146778.10,148544.96,151373.14,153393.23,EA
9,EA18,145938.49,148544.43,151348.33,152638.90,149832.52,149059.40,149267.05,148588.08,147666.73,148544.96,150038.41,152032.02,EA18
10,EA19,147359.20,149960.69,152793.47,154064.99,151149.03,150306.17,150519.76,149862.98,148958.62,149862.77,151373.14,153393.23,EA19
11,EE,612.30,642.20,643.40,642.10,576.60,548.10,584.00,593.50,600.90,605.50,622.90,624.70,EE
12,EL,4646.87,4731.34,4795.07,4856.36,4829.00,4705.48,4381.82 p,4105.22 p,3997.71 p,4034.84 p,4064.04 p,4083.03,EL
13,ES,19784.00,20609.20,21284.90,21324.10,19986.80,19639.50,19112.50,18342.60,17861.90,18039.20,18521.30 p,18987.40,ES
14,EU28,220897.89,224686.64,228889.84,231215.63,227222.35,225675.48,225986.40,225123.43,224528.80,226843.03,229324.65,232135.67,EU28
15,FI,2410.60,2454.60,2506.90,2562.70,2501.00,2483.80,2515.50,2537.60,2519.60,2507.50,2504.10,2516.60,FI
16,FR,26374.00,26664.00,27039.00,27166.00,26859.00,26888.00,27099.00,27185.00,27252.00,27373.00,27434.00 p,27612.00,FR
17,HR,1637.54 p,1689.26 p,1742.67 p,1779.87 d,1766.55 d,1699.97 d,1634.51 d,1575.51 d,1533.99 d,1575.00 d,1594.59 d,1599.19,HR
18,HU,4174.19,4192.22,4197.97,4115.47,4012.92,3969.25,3969.42,3975.80,4019.46,4213.65,4315.55,4429.45,HU
19,IE,1962.30,2053.00,2142.74,2129.25,1962.30,1882.73,1872.44 b,1861.51,1908.27,1940.41,1989.41,2045.45,IE
20,IT,24501.30,24983.80,25294.90,25349.20,24925.50,24765.70,24842.70,24764.80,24322.80,24339.40,24497.90,24809.40,IT
21,LI,:,:,:,:,:,:,:,:,36.22,36.68,36.76,,LI
22,LT,1420.72,1416.26,1445.14,1426.09,1316.51,1246.77,1252.70,1274.90,1291.89,1317.81,1334.73,1361.21,LT
23,LU,307.69,319.48,333.55,349.46,353.12,359.56,370.16,379.14,386.07,395.95,406.11,418.44,LU
24,LV,969.15,1024.95,1064.07,1055.07,903.72,843.51,856.22,868.63,888.63,876.63,889.00,886.30,LV
25,MK,587.48,614.58,632.90,682.96,713.08,687.38,697.09,705.38,744.84,762.51,:,,MK
26,MT,151.26,153.51,156.95,160.94,161.00,163.79,168.62,172.83,179.28,188.51,195.93,203.15,MT
27,NL,8339.00,8519.00,8771.00,8914.00,8838.00,8778.00,8854.00,8836.00,8732.00,8724.00,8806.00 p,8901.00,NL
28,NO,2354.00,2434.00,2535.00,2617.00,2605.00,2591.00,2630.00,2684.00,2713.00,2746.00,2757.00,2764.00,NO
29,PL,14057.00,14503.90,15155.90,15731.90,15789.40,15370.30 b,15457.30,15474.90,15463.80,15731.00,15970.00,16060.70,PL
30,PT,5040.96,5060.86,5061.58,5080.13,4941.69,4871.33,4776.73,4581.45,4450.17,4512.99,4575.82,4650.51,PT
31,RO,9267.20,9330.70,9364.80,9365.90,9181.00,9156.10,9082.20,8645.30 b,8569.40,8634.60,8525.70,8449.00,RO
32,SE,4348.70,4422.40,4524.40,4565.20,4454.80,4497.70,4593.60,4627.40,4671.80,4737.40,4807.40,4889.80,SE
33,SI,929.49,944.14,975.80,1000.82,982.90,962.10,946.02,937.24,926.70,930.03,941.56,959.74,SI
34,SK,2088.91,2132.39,2176.97,2247.14,2203.16,2169.82,2208.31,2209.43,2192.25,2223.15,2267.10,2321.05,SK
35,UK,28853.15,29140.45,29378.75,29627.56,29154.26,29226.87,29374.62,29694.53,30042.22,30752.41,31281.15,31725.39,UK

In [60]:
df["State"] = df["unit,nace_r2,na_item,geo"]


#state_geo_path = r'topojson/europe.topojson.json'
state_geo_path = r'geojson/europe.topojson'

topojson_path = os.path.join('topojson', 'europe.topojson.json')

df['test_2016'] = [i*1000 for i in range(df.shape[0])]

eu_map = folium.Map([45, 20], tiles='cartodbpositron', zoom_start=3.6)

# topojson='' try this!
eu_map.choropleth(geo_data=geo_json_data, data=df,
             columns=['State', 'test_2016'],
             key_on='feature.id',
             fill_color='BuPu', fill_opacity=0.7, line_opacity=0.2,
             legend_name='Percentage for winner of general election (%)')


folium.TopoJson(
    open(topojson_path),
    'objects.europe'
    name='topojson'
).add_to(eu_map)

folium.LayerControl().add_to(eu_map)

eu_map

SyntaxError: invalid syntax (<ipython-input-60-4259230cf012>, line 14)

In [48]:

m = folium.Map(location=[48, -102], zoom_start=3)

m.choropleth(
    geo_data=state_geo,
    name='choropleth',
    data=df,
    columns=['State', '2016'],
    key_on='feature.id',
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Unemployment Rate (%)'
)


folium.LayerControl().add_to(m)

m

TypeError: can't multiply sequence by non-int of type 'float'